# Generated by Django 5.0.6 on 2024-07-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='user_email',
            new_name='user',
        ),
    ]
