# Generated by Django 5.0.6 on 2024-07-12 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0002_rename_user_email_women_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('apple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apples.apple')),
                ('apple_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apples.appleservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
